import os.path
import datetime
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar']

class GoogleCalendarService:
    def __init__(self):
        self.creds = None
        # The file token.json stores the user's access and refresh tokens
        if os.path.exists('token.json'):
            self.creds = Credentials.from_authorized_user_file('token.json', SCOPES)

    def is_authorized(self):
        if not self.creds or not self.creds.valid:
            if self.creds and self.creds.expired and self.creds.refresh_token:
                try:
                    self.creds.refresh(Request())
                    return True
                except:
                    return False
            return False
        return True

    def get_auth_url(self):
        from google_auth_oauthlib.flow import Flow
        flow = Flow.from_client_secrets_file(
            'client_secret.json', 
            scopes=SCOPES,
            redirect_uri='http://localhost:8000/auth/callback'
        )
        auth_url, _ = flow.authorization_url(prompt='consent', access_type='offline')
        return auth_url

    def save_token_from_code(self, code):
        from google_auth_oauthlib.flow import Flow
        flow = Flow.from_client_secrets_file(
            'client_secret.json', 
            scopes=SCOPES,
            redirect_uri='http://localhost:8000/auth/callback'
        )
        flow.fetch_token(code=code)
        self.creds = flow.credentials
        with open('token.json', 'w') as token:
            token.write(self.creds.to_json())

    def create_event(self, summary, description, start_time_str, duration_mins=60):
        if not self.is_authorized():
            return {"status": "error", "message": "Not authorized"}

        try:
            service = build('calendar', 'v3', credentials=self.creds)

            start_time = datetime.datetime.fromisoformat(start_time_str)
            end_time = start_time + datetime.timedelta(minutes=duration_mins)

            event = {
                'summary': summary,
                'description': description,
                'start': {
                    'dateTime': start_time.isoformat(),
                    'timeZone': 'UTC',
                },
                'end': {
                    'dateTime': end_time.isoformat(),
                    'timeZone': 'UTC',
                },
            }

            event = service.events().insert(calendarId='primary', body=event).execute()
            return {"status": "success", "event_id": event.get('id'), "link": event.get('htmlLink')}

        except HttpError as error:
            return {"status": "error", "message": str(error)}

    def block_time(self, reason, duration_mins):
        now = datetime.datetime.utcnow().replace(microsecond=0)
        # Block from next available 15-min slot
        start_time = now + datetime.timedelta(minutes=(15 - now.minute % 15))
        return self.create_event(
            summary=f"Bio-Twin: {reason}",
            description="Automated health block generated by your Bio-Twin agent.",
            start_time_str=start_time.isoformat(),
            duration_mins=duration_mins
        )
